services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=jobboard
      - DB_USERNAME=development
      - DB_PASSWORD=PATTERNS@123
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: development
      POSTGRES_PASSWORD: PATTERNS@123
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pgsql-data:
  redis-data:
